[BE20-246] Sendgrid API async client
savonixinc/python-http-client pull request #1
Opened 2020-04-17 05:39 UTC by k-vinogradov

2020-04-17 09:10 UTC, antonmolodykh requested changes

2020-04-17 09:10 UTC, antonmolodykh commented on pytest-async.ini
> +junit_family = xunit2
Add new line please

2020-04-17 09:10 UTC, antonmolodykh commented on setup.cfg
> +junit_family = xunit2
Add new line please

2020-04-17 10:40 UTC, antonmolodykh approved these changes

2020-04-22 12:25 UTC, DrLoboto requested changes
Travis configuration makes me think that authors may miss tox-like configuration options which become critical in sync+async testing. Need to study Travis before update its configuration. Please rollback changes and leave only non async testing there for now.

Settings specific for our Jenkins job run could be placed in `tox-ci.ini` itself. The only problem is tests discovery in async env. Both tox configs can be compacted using sections approach (not line conditions one).

2020-04-22 12:25 UTC, DrLoboto commented on python_http_client/client.py
> +    http_methods = {'delete', 'get', 'patch', 'post', 'put'}
Why rename?

2020-04-22 12:25 UTC, DrLoboto commented on python_http_client/async_client.py
> +    def client_session_is_set(self) -> bool:
Why not `client_session` property with setter?

2020-04-22 12:25 UTC, DrLoboto commented on python_http_client/async_client.py
> +                        request.get_full_url(), code, body, headers, None)
Maybe use `raise_for_status` request setting instead? Are these exception signature differ? I'm a bit confused in exceptions raised in sync and async variants.

2020-04-22 12:25 UTC, DrLoboto commented on python_http_client/async_client.py
> +            return Response(response_class)
Why not subclass `Response` class to pass values directly?

2020-04-22 12:25 UTC, DrLoboto commented on tests/async_test_unit.py
> +    raise unittest.SkipTest()
Looks like wrong order of import and import possibility check.

2020-04-24 15:34 UTC, k-vinogradov commented on tests/async_test_unit.py
> +    raise unittest.SkipTest()
Fixed

2020-04-24 15:34 UTC, k-vinogradov commented on python_http_client/async_client.py
> +            return Response(response_class)
Agree. Fixed

2020-04-24 15:40 UTC, k-vinogradov commented on python_http_client/async_client.py
> +                        request.get_full_url(), code, body, headers, None)
There is [some original routine](https://github.com/savonixinc/python-http-client/blob/56b4b3d074fdc9978c09e6e755981f13e71068c3/python_http_client/async_client.py#L92) depending on the `HTTPError` exception instance. We reuse it to keep API the same. I think it's better to keep this way.

2020-04-24 15:41 UTC, k-vinogradov commented on python_http_client/async_client.py
> +    def client_session_is_set(self) -> bool:
I thought explicitly method call makes code clear. Property is ok too. Fixed.

2020-04-24 15:43 UTC, k-vinogradov commented on python_http_client/client.py
> +    http_methods = {'delete', 'get', 'patch', 'post', 'put'}
Idea was to avoid using too general words in the class with a fluent interface. Actually it isn't so needed. Reverted it back.

2020-04-27 06:09 UTC, DrLoboto commented on python_http_client/async_client.py
> +    def client_session_is_set(self) -> bool:
Explicit getters and setters bring Java stench. Cases when Python properties cannot replace them are rare enough (even in async code).

2020-04-27 06:18 UTC, DrLoboto requested changes
Almost there!

2020-04-27 06:18 UTC, DrLoboto commented on python_http_client/async_client.py
> +        if self.client_session:
I would check here `_aiohttp_client_session` itself as our only condition is session existence. Any other logic that may be applied in `client_session` getter won't affect the decision.

2020-04-27 06:18 UTC, DrLoboto commented on python_http_client/async_client.py
> +    def __init__(self, code, body, headers):
```suggestion
class AsyncResponse(Response):
    """Holds the response from an async API call."""

    def __init__(self, code, body, headers):
```

2020-04-27 06:18 UTC, DrLoboto commented on tox-ci.ini
> +       !async: pytest
Why such complication? Use same `pytest` version in all envs.

2020-05-11 08:57 UTC, DrLoboto approved these changes

2020-05-15 06:48 UTC, antonmolodykh approved these changes

2020-05-15 06:49 UTC, merged